apiVersion: apps/v1

#Deployment that containts the replica set
kind: Deployment
metadata: 
  name: db
  labels:
    app: db

#Replica set that deploys two pods
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: db
#Template for the pods. It de ploys a container with redis image on port 6379
  template:
    metadata: 
      labels:
        app: db
    spec:
      containers: 
        - name: db
          image: redis
          ports: 
            - containerPort: 6379

---

#Service that connects containers trough the target port
apiVersion: v1
kind: Service
metadata: 
  name: db-service
  labels:
    app: db
spec: 
  selector: 
    app: db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: http
  