apiVersion: apps/v1

#Deployment that containts the replica set
kind: Deployment
metadata: 
  name: api
  labels:
    app: api

#Replica set that deploys two pods
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: api

#Template for the pods. It de ploys a container with custom docker Image on port 80
  template:
    metadata: 
      labels:
        app: api
    spec:
      containers: 
        - name: nginx
          image: schasqui/api_kub2:latest
          ports: 
            - containerPort: 80

---

#MetalLB that redirects the traffic from IP 10.64.140.44 to the pods previously deffined
apiVersion: v1
kind: Service
metadata: 
  name: api-service
  labels:
    app: api
spec: 
  selector: 
    app: api
  type: LoadBalancer
  loadBalancerIP: 10.64.140.44
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  