apiVersion: apps/v1
kind: Deployment
metadata: 
  name: db
  labels:
    app: db
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: db
  template:
    metadata: 
      labels:
        app: db
    spec:
      containers: 
        - name: db
          image: redis
          ports: 
            - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata: 
  name: db-service
  labels:
    app: db
spec: 
  selector: 
    app: db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: http
  